version: 2
updates:
  - package-ecosystem: 'npm'
    versioning-strategy: 'increase'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      dependencies-non-major:
        dependency-type: 'production'
        update-types:
          - 'patch'
          - 'minor'
      dependencies-major:
        dependency-type: 'production'
        update-types:
          - 'major'
      devDependencies-non-major:
        dependency-type: 'development'
        update-types:
          - 'patch'
          - 'minor'
      devDependencies-major:
        dependency-type: 'development'
        update-types:
          - 'major'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - node
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - redis
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
