services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - '${VALKEY_PORT}:${VALKEY_PORT}'
    environment:
      VALKEY_EXTRA_FLAGS: '--port ${VALKEY_PORT} --requirepass ${VALKEY_PASSWORD}'
