import FORM_STEPS from "../constants/formSteps";
import paths from "../constants/paths";

interface TaskStepDefinition {
    path: string; 
    dependsOn: string[];
}

type TaskFlowMapType = Record<string, TaskStepDefinition>;

const TASK_FLOW_MAP : TaskFlowMapType = {
  [FORM_STEPS.START]: {
    path: paths.START,
    dependsOn: [],
  },
  [FORM_STEPS.SAFETY_CHECK]: {
    path: paths.SAFETY_CHECK,
    dependsOn: [FORM_STEPS.START],
  },
  [FORM_STEPS.NOT_SAFE]: {
    path: paths.NOT_SAFE,
    dependsOn: [FORM_STEPS.SAFETY_CHECK],
  },
  [FORM_STEPS.CHILDREN_SAFETY_CHECK]: {
    path: paths.CHILDREN_SAFETY_CHECK,
    dependsOn: [FORM_STEPS.SAFETY_CHECK],
  },
  [FORM_STEPS.CHILDREN_NOT_SAFE]: {
    path: paths.CHILDREN_NOT_SAFE,
    dependsOn: [FORM_STEPS.CHILDREN_SAFETY_CHECK],
  },
  [FORM_STEPS.DO_WHATS_BEST]: {
    path: paths.DO_WHATS_BEST,
    dependsOn: [FORM_STEPS.CHILDREN_SAFETY_CHECK],
  },
  [FORM_STEPS.COURT_ORDER_CHECK]: {
    path: paths.COURT_ORDER_CHECK,
    dependsOn: [FORM_STEPS.DO_WHATS_BEST],
  },
  [FORM_STEPS.EXISTING_COURT_ORDER]: {
    path: paths.EXISTING_COURT_ORDER,
    dependsOn: [FORM_STEPS.COURT_ORDER_CHECK],
  },
  [FORM_STEPS.NUMBER_OF_CHILDREN]: {
    path: paths.NUMBER_OF_CHILDREN,
    dependsOn: [FORM_STEPS.COURT_ORDER_CHECK],
  },
  [FORM_STEPS.ABOUT_THE_CHILDREN]: {
    path: paths.ABOUT_THE_CHILDREN,
    dependsOn: [FORM_STEPS.NUMBER_OF_CHILDREN],
  },
  [FORM_STEPS.ABOUT_THE_ADULTS]: {
    path: paths.ABOUT_THE_ADULTS,
    dependsOn: [FORM_STEPS.ABOUT_THE_CHILDREN],
  },
  [FORM_STEPS.TASK_LIST]: {
    path: paths.TASK_LIST,
    dependsOn: [FORM_STEPS.ABOUT_THE_ADULTS],
  },
  [FORM_STEPS.LIVING_VISITING_MOSTLY_LIVE]: { 
    path: paths.LIVING_VISITING_MOSTLY_LIVE,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN]: { 
    path: paths.LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN,
    dependsOn: [FORM_STEPS.LIVING_VISITING_MOSTLY_LIVE],
  },
  [FORM_STEPS.LIVING_VISITING_WHICH_DAYS_OVERNIGHT]: { 
    path: paths.LIVING_VISITING_WHICH_DAYS_OVERNIGHT,
    dependsOn: [FORM_STEPS.LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN],
  },
  [FORM_STEPS.LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN]: { 
    path: paths.LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN,
    dependsOn: [FORM_STEPS.LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN],
  },
  [FORM_STEPS.LIVING_VISITING_WHICH_DAYS_DAYTIME_VISITS]: { 
    path: paths. LIVING_VISITING_WHICH_DAYS_DAYTIME_VISITS,
    dependsOn: [FORM_STEPS.LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN],
  },
  [FORM_STEPS.LIVING_VISITING_WHICH_SCHEDULE]: { 
    path: paths.LIVING_VISITING_WHICH_SCHEDULE,
    dependsOn: [FORM_STEPS.LIVING_VISITING_MOSTLY_LIVE ],
  },
  [FORM_STEPS.HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS]: { 
    path: paths.HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.HANDOVER_HOLIDAYS_WHERE_HANDOVER]: {
    path: paths.HANDOVER_HOLIDAYS_WHERE_HANDOVER,
    dependsOn: [FORM_STEPS.HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS],
  },
  [FORM_STEPS.HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS]: {
    path: paths.HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS,
    dependsOn: [FORM_STEPS.HANDOVER_HOLIDAYS_WHERE_HANDOVER],
  },
  [FORM_STEPS.HANDOVER_HOLIDAYS_HOW_CHANGE_DURING_SCHOOL_HOLIDAYS]: {
    path: paths.HANDOVER_HOLIDAYS_HOW_CHANGE_DURING_SCHOOL_HOLIDAYS,
    dependsOn: [FORM_STEPS.HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS ],
  },
  [FORM_STEPS.HANDOVER_HOLIDAYS_ITEMS_FOR_CHANGEOVER]: {
    path: paths.HANDOVER_HOLIDAYS_ITEMS_FOR_CHANGEOVER,
    dependsOn: [FORM_STEPS.HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS],
  },
  [FORM_STEPS.SPECIAL_DAYS_WHAT_WILL_HAPPEN]: {
    path: paths.SPECIAL_DAYS_WHAT_WILL_HAPPEN,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.OTHER_THINGS_WHAT_OTHER_THINGS_MATTER]: {
    path: paths.OTHER_THINGS_WHAT_OTHER_THINGS_MATTER,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.DECISION_MAKING_PLAN_LAST_MINUTE_CHANGES]: {
    path: paths.DECISION_MAKING_PLAN_LAST_MINUTE_CHANGES,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.DECISION_MAKING_PLAN_LONG_TERM_NOTICE]: {
    path: paths.DECISION_MAKING_PLAN_LONG_TERM_NOTICE,
    dependsOn: [FORM_STEPS.DECISION_MAKING_PLAN_LAST_MINUTE_CHANGES],
  },
  [FORM_STEPS.DECISION_MAKING_PLAN_REVIEW]: {
    path: paths.DECISION_MAKING_PLAN_REVIEW,
    dependsOn: [FORM_STEPS.DECISION_MAKING_PLAN_LONG_TERM_NOTICE],
  },
  [FORM_STEPS.CHECK_YOUR_ANSWERS]: {
    path: paths.CHECK_YOUR_ANSWERS,
    dependsOn: [FORM_STEPS.TASK_LIST],
  },
  [FORM_STEPS.SHARE_PLAN]: {
    path: paths.SHARE_PLAN,
    dependsOn: [FORM_STEPS.CHECK_YOUR_ANSWERS],
  },
  [FORM_STEPS.CONFIRMATION]: {
    path: paths.CONFIRMATION,
    dependsOn: [FORM_STEPS.SHARE_PLAN],
  },

};

export default TASK_FLOW_MAP;