apiVersion: v1
kind: Secret
metadata:
  name: ${KUBE_NAMESPACE}-secrets
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  SESSION_SECRET: '${SESSION_SECRET}'
  BETA_ACCESS_PASSWORDS: '${BETA_ACCESS_PASSWORDS}'
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: Opaque
data:
  auth: "${BASIC_AUTH_BASE64}"
