apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: care-arrangement-plan-dev
  labels:
    app: care-arrangement-plan-dev
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: care-arrangement-plan-dev
