apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${KUBE_NAMESPACE}-hpa
  namespace: ${KUBE_NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${KUBE_NAMESPACE}-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
