enum formFields {
  SAFETY_CHECK = 'safety-check',
  CHILDREN_SAFETY_CHECK = 'children-safety-check',
  DO_WHATS_BEST = 'do-whats-best',
  COURT_ORDER_CHECK = 'court-order-check',
  NUMBER_OF_CHILDREN = 'number-of-children',
  PASSWORD = 'password',
  CHILD_NAME = 'child-name',
  INITIAL_ADULT_NAME = 'initial-adult-name',
  SECONDARY_ADULT_NAME = 'secondary-adult-name',
  MOSTLY_LIVE_WHERE = 'mostly-live-where',
  MOSTLY_LIVE_DESCRIBE_ARRANGEMENT = 'mostly-live-describe-arrangement',
  WHICH_SCHEDULE = 'which-schedule',
  WILL_OVERNIGHTS_HAPPEN = 'will-overnights-happen',
  WHICH_DAYS_OVERNIGHT = 'which-days-overnight',
  WHICH_DAYS_OVERNIGHT_DESCRIBE_ARRANGEMENT = 'which-days-overnight-describe-arrangement',
  WILL_DAYTIME_VISITS_HAPPEN = 'will-daytime-visits-happen',
  WHICH_DAYS_DAYTIME_VISITS = 'which-days',
  WHICH_DAYS_DAYTIME_VISITS_DESCRIBE_ARRANGEMENT = 'which-days-describe-arrangement',
  GET_BETWEEN_HOUSEHOLDS = 'get-between-households',
  GET_BETWEEN_HOUSEHOLDS_DESCRIBE_ARRANGEMENT = 'get-between-households-describe-arrangement',
  WHERE_HANDOVER = 'where-handover',
  WHERE_HANDOVER_SOMEONE_ELSE = 'where-handover-someone-else',
  WILL_CHANGE_DURING_SCHOOL_HOLIDAYS = 'will-change-during-school-holidays',
  SPECIAL_DAYS = 'special-days',
}

export default formFields
