const FORM_STEPS = {
    START: 'step1',
    SAFETY_CHECK: 'step2',
    NOT_SAFE: 'step2A',
    CHILDREN_SAFETY_CHECK: 'step3',
    CHILDREN_NOT_SAFE: 'step3A',
    DO_WHATS_BEST: 'step4',
    COURT_ORDER_CHECK: 'step5',
    EXISTING_COURT_ORDER: 'step5A',
    NUMBER_OF_CHILDREN: 'step6',
    ABOUT_THE_CHILDREN: 'step7',
    ABOUT_THE_ADULTS: 'step8',
    TASK_LIST: 'step9',
    LIVING_VISITING_MOSTLY_LIVE: 'step10_living_and_visiting',
    LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN: 'step10_living_and_visiting_A_1',
    LIVING_VISITING_WHICH_DAYS_OVERNIGHT: 'step10_living_and_visiting_A_1A',
    LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN: 'step10_living_and_visiting_A_2',   
    LIVING_VISITING_WHICH_DAYS_DAYTIME_VISITS: 'step10_living_and_visiting_A_3',
    LIVING_VISITING_WHICH_SCHEDULE: 'step10_living_and_visiting_B',
    HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS: 'step10_handovers_and_holidays_1',
    HANDOVER_HOLIDAYS_WHERE_HANDOVER: 'step10_handovers_and_holidays_2',
    HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS: 'step10_handovers_and_holidays_3',
    HANDOVER_HOLIDAYS_HOW_CHANGE_DURING_SCHOOL_HOLIDAYS: 'step10_handovers_and_holidays_3A',
    HANDOVER_HOLIDAYS_ITEMS_FOR_CHANGEOVER: 'step10_handovers_and_holidays_4',
    SPECIAL_DAYS_WHAT_WILL_HAPPEN: 'step10_special_days',
    OTHER_THINGS_WHAT_OTHER_THINGS_MATTER: 'step10_other_things',
    DECISION_MAKING_PLAN_LAST_MINUTE_CHANGES: 'step10_decision_making_1',
    DECISION_MAKING_PLAN_LONG_TERM_NOTICE: 'step10_decision_making_2',
    DECISION_MAKING_PLAN_REVIEW: 'step10_decision_making_3',
    CHECK_YOUR_ANSWERS: 'step11',
    SHARE_PLAN: 'step12',
    CONFIRMATION: 'step13',
}

export default FORM_STEPS;