export default {
  START: '/',
  SAFETY_CHECK: '/safety-check',
  NOT_SAFE: '/not-safe',
  CHILDREN_SAFETY_CHECK: '/children-safety-check',
  CHILDREN_NOT_SAFE: '/children-not-safe',
  DO_WHATS_BEST: '/do-whats-best',
  COURT_ORDER_CHECK: '/court-order-check',
  EXISTING_COURT_ORDER: '/existing-court-order',
  NUMBER_OF_CHILDREN: '/number-of-children',
  ABOUT_THE_CHILDREN: '/about-the-children',
  ABOUT_THE_ADULTS: '/about-the-adults',
  TASK_LIST: '/make-a-plan',
  CHECK_YOUR_ANSWERS: '/check-your-answers',
  SHARE_PLAN: '/share-plan',
  PASSWORD: '/password',
  LIVING_VISITING_MOSTLY_LIVE: '/living-and-visiting/where-will-the-children-mostly-live',
  LIVING_VISITING_WHICH_SCHEDULE: '/living-and-visiting/which-schedule-is-best',
  LIVING_VISITING_WHICH_SCHEDULE_SKIP: '/living-and-visiting/which-schedule-is-best/skip',
  LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN: '/living-and-visiting/will-overnights-happen',
  LIVING_VISITING_WHICH_DAYS_OVERNIGHT: '/living-and-visiting/which-days-overnight',
  LIVING_VISITING_WHICH_DAYS_OVERNIGHT_SKIP: '/living-and-visiting/which-days-overnight/skip',
  LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN: '/living-and-visiting/will-daytime-visits-happen',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN: '/special-days/what-will-happen',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN_SKIP: '/special-days/what-will-happen/skip',
}
