export default {
  START: '/',
  COOKIES: '/cookies',
  SAFETY_CHECK: '/safety-check',
  NOT_SAFE: '/not-safe',
  CHILDREN_SAFETY_CHECK: '/children-safety-check',
  CHILDREN_NOT_SAFE: '/children-not-safe',
  DO_WHATS_BEST: '/do-whats-best',
  COURT_ORDER_CHECK: '/court-order-check',
  EXISTING_COURT_ORDER: '/existing-court-order',
  NUMBER_OF_CHILDREN: '/number-of-children',
  ABOUT_THE_CHILDREN: '/about-the-children',
  ABOUT_THE_ADULTS: '/about-the-adults',
  TASK_LIST: '/make-a-plan',
  CHECK_YOUR_ANSWERS: '/check-your-answers',
  SHARE_PLAN: '/share-plan',
  PASSWORD: '/password',
  LIVING_VISITING_MOSTLY_LIVE: '/living-and-visiting/where-will-the-children-mostly-live',
  LIVING_VISITING_WHICH_SCHEDULE: '/living-and-visiting/which-schedule-is-best',
  LIVING_VISITING_WHICH_SCHEDULE_NOT_REQUIRED: '/living-and-visiting/which-schedule-is-best/not-required',
  LIVING_VISITING_WILL_OVERNIGHTS_HAPPEN: '/living-and-visiting/will-overnights-happen',
  LIVING_VISITING_WHICH_DAYS_OVERNIGHT: '/living-and-visiting/which-days-overnight',
  LIVING_VISITING_WHICH_DAYS_OVERNIGHT_NOT_REQUIRED: '/living-and-visiting/which-days-overnight/not-required',
  LIVING_VISITING_WILL_DAYTIME_VISITS_HAPPEN: '/living-and-visiting/will-daytime-visits-happen',
  LIVING_VISITING_WHICH_DAYS_DAYTIME_VISITS: '/living-and-visiting/which-days-daytime-visits',
  LIVING_VISITING_WHICH_DAYS_DAYTIME_VISITS_NOT_REQUIRED: '/living-and-visiting/which-days-daytime-visits/not-required',
  HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS: '/handover-and-holidays/get-between-households',
  HANDOVER_HOLIDAYS_GET_BETWEEN_HOUSEHOLDS_NOT_REQUIRED: '/handover-and-holidays/get-between-households/not-required',
  HANDOVER_HOLIDAYS_WHERE_HANDOVER: '/handover-and-holidays/where-handover',
  HANDOVER_HOLIDAYS_WHERE_HANDOVER_NOT_REQUIRED: '/handover-and-holidays/where-handover/not-required',
  HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS: '/handover-and-holidays/will-change-during-school-holidays',
  HANDOVER_HOLIDAYS_WILL_CHANGE_DURING_SCHOOL_HOLIDAYS_NOT_REQUIRED:
    '/handover-and-holidays/will-change-during-school-holidays/not-required',
  HANDOVER_HOLIDAYS_HOW_CHANGE_DURING_SCHOOL_HOLIDAYS: '/handover-and-holidays/how-change-during-school-holidays',
  HANDOVER_HOLIDAYS_HOW_CHANGE_DURING_SCHOOL_HOLIDAYS_NOT_REQUIRED:
    '/handover-and-holidays/how-change-during-school-holidays/not-required',
  HANDOVER_HOLIDAYS_ITEMS_FOR_CHANGEOVER: '/handover-and-holidays/items-for-changeover',
  HANDOVER_HOLIDAYS_ITEMS_FOR_CHANGEOVER_NOT_REQUIRED: '/handover-and-holidays/items-for-changeover/not-required',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN: '/special-days/what-will-happen',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN_NOT_REQUIRED: '/special-days/what-will-happen/not-required',
  DOWNLOAD_PDF: '/download-pdf',
  PRINT_PDF: '/print-pdf',
}
