export default {
  START: '/',
  SAFETY_CHECK: '/safety-check',
  NOT_SAFE: '/not-safe',
  CHILDREN_SAFETY_CHECK: '/children-safety-check',
  CHILDREN_NOT_SAFE: '/children-not-safe',
  DO_WHATS_BEST: '/do-whats-best',
  COURT_ORDER_CHECK: '/court-order-check',
  EXISTING_COURT_ORDER: '/existing-court-order',
  NUMBER_OF_CHILDREN: '/number-of-children',
  ABOUT_THE_CHILDREN: '/about-the-children',
  ABOUT_THE_ADULTS: '/about-the-adults',
  TASK_LIST: '/make-a-plan',
  CHECK_YOUR_ANSWERS: '/check-your-answers',
  SHARE_PLAN: '/share-plan',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN: '/special-days/what-will-happen',
  SPECIAL_DAYS_WHAT_WILL_HAPPEN_SKIP: '/special-days/what-will-happen/skip',
}
