name: Deploy to Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'change-to-main-when-ready-to-deploy'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: 'Image'
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_dev:
    name: 'Development'
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [image]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_production:
    name: 'Production'
    needs: [image, deploy_dev]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit
