steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'fromFile'
      versionFilePath: '.nvmrc'

  - script: npm install -g npm@latest
    displayName: 'Update npm'

  - script: npx audit-ci --config audit-ci.json
    displayName: 'Run vulnerability scan'

  - script: npm ci
    displayName: 'Install Dependencies'

  - script: npm run lint
    displayName: 'Run Linter'

  - script: npm run prettier
    displayName: 'Run Prettier'

  - script: terraform fmt -check -recursive
    displayName: 'Check Terraform Formatting'

  - script: npm run test:ci
    displayName: 'Run Unit Tests'

  - script: |
      while IFS='=' read -r key value; do export "$key"="$value"; done < .env.test
      npm run int-test:ci
    displayName: 'Run Integration Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: 'test-results/**/*.xml'
