trigger:
  - main

variables:
  - name: ecrRepositoryName
    value: pfl-care-arrangement-plan

stages:
  - stage: Validation
    jobs:
      - job: ValidationJob
        pool: Default
        steps:
          - template: templates/validation.yml
  - stage: development
    displayName: Deploy to Test
    jobs:
      - job: DeployTest
        pool: Default
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: 'Dockerfile'
              buildContext: '.'
              repository: 'pfl-care-arrangement-plan'
              tags: $(Build.SourceVersion)
          - task: ECRPushImage@1
            displayName: 'Push Docker Image to ECR'
            inputs:
              awsCredentials: 'aws-oidc-federation'
              regionName: 'eu-west-2'
              sourceImageName: 'pfl-care-arrangement-plan'
              sourceImageTag: $(Build.SourceVersion)
              repositoryName: $(ecrRepositoryName)
              pushTag: $(Build.SourceVersion)
          - script: echo 'hello, world'
            displayName: 'Run script'
  - stage: production
    displayName: Deploy to Production
    trigger: manual
    jobs:
      - job: DeployProd
        pool: Default
        steps:
          - script: echo 'hello, world'
            displayName: 'Run script'
