schedules:
  - cron: '0 3 * * *'
    displayName: 'Every day at 3am (UTC)'
    branches:
      include: [main]
    always: true

trigger: none

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'fromFile'
      versionFilePath: '.nvmrc'

  - script: npx renovate
    displayName: 'Run Renovate'
    env:
      RENOVATE_CACHE_DIR: /var/tmp
      RENOVATE_AUTODISCOVER: true
      RENOVATE_PLATFORM: azure
      RENOVATE_ENDPOINT: $(System.CollectionUri)
      RENOVATE_TOKEN: $(System.AccessToken)
